### ISSUE TITLE
Fix recurrence in event generator

### ISSUE THREAD

**Issue by yhpoh91** [cs2103aug2015-F11-4j/main#111]
use the Recurrence enum

**Comment by shanrajapakshe-zz** [comment]
implement when parsedCommand takes on the recurrence enum
(call parsedCommand.getReccurence() or something similar)

ABOVE FORMAT CHANGED - 2015-11-05

**Comment by shanrajapakshe-zz** [comment]
Issue resolved in commit: "Added functionality for new format of recurrence" on 11/05/2015
commit ID: ebe3c3f8fcb219b33cc999c689ba0b7c8ac3dd06
